apiVersion: config.nri/v1alpha1
kind: TopologyAwareConfig
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topology-aware-plugin.labels" . | nindent 4 }}
topologyAware:
  {{- toYaml .Values.config.policy | nindent 2 }}
common:
  {{- toYaml .Values.config.common | nindent 2 }}
