apiVersion: config.nri/v1alpha1
kind: BalloonsConfig
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "balloons-plugin.labels" . | nindent 4 }}
balloons:
  {{- toYaml .Values.policyConfig | nindent 2 }}
common:
  {{- toYaml .Values.commonConfig | nindent 2 }}
