apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nri-resource-policy-generic
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nri-plugin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - config.nri
  resources:
  - genericpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.nri
  resources:
  - genericpolicies/status
  verbs:
  - get
  - update
  - patch
