name: Publish Helm charts

on:
  push:
    tags:
      - "v*.*.*"

env:
  CHARTS_DIR: deployment/helm/resource-management-policies/


jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package Helm charts
        run: |
          helm package "$CHARTS_DIR"/*

      - name: Upload Helm packages to GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          draft: true
          append_body: true
          files: nri-resource-policy-*.tgz
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
