name: Project Checks

on:
  push:
    branches:
      - main
      - "release/**"
      - "test/**"
  pull_request:
    branches:
      - main
      - "release/**"

env:
  GO_VERSION: "1.20.10"

jobs:
  verify:
    name: Minimal PR Verification
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Git-check PR for conflict markers and trailing whitespace errors.
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch -q origin ${{ github.base_ref }}
          if ! git diff-index --check origin/${{ github.base_ref }} --; then
              echo "This PR would introduce the above errors."
              echo "Please fix them and update the PR."
              exit 1
          fi
      - name: make verify
        run: |
          make verify

      - name: Build docs
        run: |
          make site-build
          make clean-html

      - name: Install gh-pages build dependencies
        run: |
          pip3 install --user -r docs/requirements.txt
          echo "`python3 -m site --user-base`/bin" >> $GITHUB_PATH

      - name: Verify update of gh-pages
        run: |
          git config user.name "Github"
          git config user.email "no-reply@github.com"
          ./scripts/build/update-gh-pages.sh
