name: Publish documentation

on:
  push:
    branches:
        - main
        - release-*
    tags:
        - v[0-9]+.[0-9]+.[0-9]+

concurrency:
  group: gh-pages

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Install build dependencies
      run: |
        mkdir -p build
        python3 -m venv ./build/docs
        . ./build/docs/bin/activate
        ./build/docs/bin/pip3 install -r docs/requirements.txt

    - name: Add docs from this revision to gh-pages
      run: |
        git config user.name "Github"
        git config user.email "no-reply@github.com"
        . ./build/docs/bin/activate
        ./scripts/build/update-gh-pages.sh

    - name: Publish/push to gh-pages
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin gh-pages
